sonar.projectKey=fitness-microservices
sonar.projectName=Fitness Microservices
sonar.projectVersion=1.0

sonar.sources=frontend,services,k8s,argocd,terraform,Jenkinsfile,docker-compose.yml
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/.terraform/**,**/*.tfstate,**/*.tfstate.*,**/.terraform.lock.hcl
