apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fitness-microservices
  namespace: argocd
  labels:
    app.kubernetes.io/name: fitness-microservices
spec:
  project: fitness
  source:
    repoURL: https://github.com/victoreze07/fitness-microservices-app.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: fitness
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
